-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- Source: ~/.config/hypr/monitors.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("monitors")
-- Source: ~/.config/hypr/aliases.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("aliases")
-- Source: ~/.config/hypr/autostart.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("autostart")
-- Source: ~/.config/hypr/enviroment-variables.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("enviroment-variables")
-- Source: ~/.config/hypr/permissions.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("permissions")
-- Source: ~/.config/hypr/lookandfeel.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("lookandfeel")
-- Source: ~/.config/hypr/input.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("input")
-- Source: ~/.config/hypr/binds.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("binds")
-- Source: ~/.config/hypr/windows-and-workspaces.conf — convert this file to Lua and ensure it is on Lua's package.path.
require("windows-and-workspaces")

hl.config({
    xwayland = {
        force_zero_scaling = true,
    },
})

