-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 6
-- Kikapcsolás 0  másodperc után
-- Ébredés bármire
hl.config({
    general = {
        -- Ha a gép elmegy aludni, ez biztosan leállítja a plusz hypridle-t
        after_sleep_cmd = "pkill -f \"hypridle --config " .. HOME .. "/.config/hypr/screenoff.conf\"",
    },
})

