# vim:ft=kitty

## name:     Catppuccin Kitty Latte (Dark Espresso Edition)
## author:   Catppuccin Org (Customized)
## license:  MIT
## blurb:    Soothing warm dark coffee theme for Latte!

# The basic colors
foreground              #e6dfd5
background              #1c1917
selection_foreground    #1c1917
selection_background    #fe640b

# Cursor colors
cursor                  #fe640b
cursor_text_color       #e6dfd5

# URL underline color when hovering with mouse
url_color               #fe640b

# Kitty window border colors
active_border_color     #7287fd
inactive_border_color   #4a443f
bell_border_color       #df8e1d

# OS Window titlebar colors
wayland_titlebar_color system
macos_titlebar_color system

# Tab bar colors
active_tab_foreground   #e6dfd5
active_tab_background   #fe640b
inactive_tab_foreground #a6adc8
inactive_tab_background #313244
tab_bar_background      #11111b

# Colors for marks (marked text in the terminal)
mark1_foreground #1c1917
mark1_background #7287fd
mark2_foreground #1c1917
mark2_background #8839ef
mark3_foreground #1c1917
mark3_background #209fb5

# The 16 terminal colors

# black
color0 #3e3835
color8 #5a524e

# red
color1 #f38ba8
color9 #f38ba8

# green
color2  #a6e3a1
color10 #a6e3a1

# yellow
color3  #f9e2af
color11 #f9e2af

# blue
color4  #89b4fa
color12 #89b4fa

# magenta
color5  #f5c2e7
color13 #f5c2e7

# cyan
color6  #94e2d5
color14 #94e2d5

# white
color7  #a6adc8
color15 #bac2de