exec-once = awww-daemon
exec-once = sleep 0.5 && awww img ~/.config/wallpaper_arch.png --transition-type grow --transition-pos 0.5,0.5
exec-once = hyprctl setcursor catppuccin-macchiato-dark-cursors 24
exec-once = waybar
exec-once = swaync
exec-once = clipse --listen
