-- Generated by nwg-displays on 2026-04-24 at 14:09:44. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "desc:BOE 0x0A7C",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = "1.0",
})

hl.monitor({
    output = "desc:BNQ BenQ GL2450 J5F02362019",
    mode = "1920x1080@60.0",
    position = "1920x0",
    scale = "1.0",
})


hl.monitor({
    output = "desc:Chimei Innolux Corporation 0x15E7",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = "1.25",
})
