-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("HYPRCURSOR_THEME", "catppuccin-macchiato-lavender-cursors")
hl.env("HYPRCURSOR_SIZE", "24")

--fallback

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
