-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

-- TODO: manual review — unknown section 'listener {' on line 6
hl.config({
    general = {
        -- Avoid needing an extra keypress after resume
        after_sleep_cmd = "hyprctl dispatch dpms on",
    },
})

