-- Generated by nwg-displays on 2026-04-24 at 14:09:44. Do not edit manually.

-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.monitor({
    output = "",
    mode = "1920x1080@60.0",
    position = "0x0",
    scale = "1.25",
})

