general {
    # Ha a gép elmegy aludni, ez biztosan leállítja a plusz hypridle-t
    after_sleep_cmd = pkill -f "hypridle --config $HOME/.config/hypr/screenoff.conf"
}

listener {
    timeout = 1
    # Kikapcsolás 0  másodperc után
    on-timeout = hyprctl dispatch dpms off && brightnessctl -d *kbd_backlight* set 0
    # Ébredés bármire
    on-resume = hyprctl dispatch dpms on && brightnessctl -d *kbd_backlight* set 100 && pkill -f "hypridle --config $HOME/.config/hypr/screenoff.conf"
}
