#Font colors are in ~/.config/kitty/no-preference-theme.auto.conf

#Fonts
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
symbol_map U+23FB-U+23FE,U+2B58,U+E200-U+E2A9,U+E300-U+E3E3,U+E5FA-U+E634,U+E700-U+E7C5,U+ED00-U+F2FF,U+E0A3,U+E0B4-U+E0C8,U+E0CA,U+E0CC-U+E0D2,U+E0D4,U+F000-U+F2E0,U+2665,U+26A1,U+F400-U+F4A8,U+F67C,U+E000-U+E00A,U+F300-U+F313,U+E5FA-U+E62B Twitter Color Emoji
symbol_map U+1F300-U+1Faff Twitter Color Emoji


#Cursor
cursor_shape_unfocused unchanged
cursor_stop_blinking_after 0
shell_integration no-cursor

#Scollbar
scrollbar never

#Mouse
mouse_hide_wait 5.0
mouse_map right press ungrabbed paste_selection_or_clipboard


#URLs
url_style straight
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty sftp ssh
open_url_with default
detect_urls yes
paste_actions quote-urls-at-prompt,confirm-if-large

show_hyperlink_targets yes
underline_hyperlinks always

strip_trailing_spaces always

select_by_word_characters @-./_~?&=%+#

#Performance
sync_to_monitor yes

#Terminal bell

enable_audio_bell no
bell_on_tab "🔔 "

#Background
dynamic_background_opacity yes
background_opacity 0.90

confirm_os_window_close 0
