exec-once = awww-daemon
exec-once = hyprctl setcursor nord-dark-cursors 24
exec-once = waybar
exec-once = swaync
exec-once = clipse --listen
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = [workspace special:magic silent] qbittorrent
exec-once = udiskie
