-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.env("HYPRCURSOR_THEME", "default")
hl.env("HYPRCURSOR_SIZE", "24")

--fallback

hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")

-- Steam natív, pixelmentes 1.25-ös skálázásának kényszerítése
hl.env("STEAM_FORCE_DESKTOPUI_SCALING", "1.25")

