--variables
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

local wall = "~/.config/wallpaper_arch.png"

-- BACKGROUND

-- TODO: manual review — unknown section 'background {' on line 7

-- TIME

-- TODO: manual review — unknown section 'label {' on line 22

-- GENERAL

-- TODO: manual review — unknown section 'label {' on line 45

-- TODO: manual review — unknown section 'input-field {' on line 57
hl.config({
    general = {
        no_fade_in = false,
        grace = 0,
        disable_loading_bar = true,
    },
    -- USER
    -- INPUT FIELD
})

